export default defineAppConfig({
  ui: {

  },
  icon: {
    size: '20px',
    class: 'svg-icon',
    aliases: {
      'spinner': 'svg-spinners:3-dots-scale-middle',
      'email': 'lucide:mail',
      'dashboard': 'lucide:building-2',
      'knowledge': 'lucide:book-open',
      'staff': 'lucide:users-round',
      'storage': 'lucide:hard-drive',
      'notifications': 'lucide:bell',
      'me': 'lucide:user',
      'signout': 'lucide:power',
      'appearances': 'lucide:paintbrush',
      'security': 'lucide:key-square',
      'integrations': 'lucide:cable',
      'chevron-right': 'lucide:chevron-right',
      'password': 'lucide:lock',
      'settings': 'lucide:settings',
      'portfolio': 'lucide:folder',
      'folder': 'lucide:folder',
      'folder-open': 'lucide:folder-open',
      'project': 'lucide:square-square',
      'projects': 'lucide:folders',
      'stickers': 'lucide:files',
      'filters': 'lucide:filter',
      'expand': 'lucide:expand',
      'plus': 'lucide:plus',
      'archive': 'lucide:archive',
      'search': 'lucide:search',
      'menu': 'lucide:menu',
      'square': 'lucide:square',
      'square-plus': 'lucide:square-plus',
      'square-check': 'lucide:square-check',
      'play': 'lucide:play',
      'clock': 'lucide:clock',
      'files': 'lucide:files',
      'logs': 'lucide:logs',
      'substickers': 'lucide:file-stack',
      'star': 'lucide:star',
      'fullscreen': 'lucide:fullscreen',
      'google-sheets': 'logos:google-calendar',
      'google-docs': 'logos:google-calendar',
      'google-calendar': 'logos:google-calendar',
      'google-forms': 'logos:google-calendar',
      'yandex-calendar': 'logos:google-calendar',
      'empty': 'lucide:search',
      'text': 'lucide:a-large-small',
      'edit': 'lucide:pencil',
      'delete': 'lucide:trash-2',
      'check': 'lucide:check',
    },
  },
})
