export default {
  wrapper: {
    'base': 'rounded relative select-none transition-all shadow-[inset_0_0_0_0_rgba(0,0,0,0.05)] flex-shrink-0 shrink-0 z-1 group bg-backgrounds-secondary [&.is-last]:font-semibold [&.avatars-items]:hover:-translate-x-2.5',
    'xs': 'h-xs w-xs text-xs',
    'sm': 'h-sm w-sm text-sm',
    'md': 'h-md w-md text-md',
    'lg': 'h-lg w-lg text-lg',
    'xl': 'h-xl w-xl text-xl',
    '2xl': 'h-[90px] w-[90px] text-xl',
    '3xl': 'h-[135px] w-[135px] text-xl',
  },
  loading: {
    base: 'absolute w-full top-0 left-0 h-full rounded-inherit flex flex-center',
  },
  avatar: {
    base: 'overflow-hidden flex flex-center rounded-inherit w-full h-full',
  },
  img: {
    base: 'w-full h-auto aspect-square block rounded-inherit transition-all group-hover:scale-110 group-hover:shadow-[inset_0_0_40px_0_rgba(0,0,0,0.04)]',
  },
  placeholders: {
    base: 'leading-none truncate uppercase group-[&.is-last]:bg-black/50 group-[&.is-last]:w-full group-[&.is-last]:h-full group-[&.is-last]:flex group-[&.is-last]:flex-center group-[&.is-last]:text-white group-[&.is-last]:absolute group-[&.is-last]:top-0 group-[&.is-last]:left-0 group-[&.is-last]:rounded-inherit',
  },
  icons: {
    'xs': '0.725rem',
    'sm': '0.925rem',
    'md': '1.15rem',
    'lg': '1.375rem',
    'xl': '1.5rem',
    '2xl': '1.625rem',
    '3xl': '1.8rem',
  },
  badges: {
    'base': 'absolute rounded-full ring-backgrounds-primary',
    'xs': 'h-1 w-1 ring-1',
    'sm': 'h-1.5 w-1.5 ring-2',
    'md': 'h-2 w-2 ring-3',
    'lg': 'h-2.5 w-2.5 ring-4',
    'xl': 'h-3 w-3 ring-5',
    '2xl': 'h-4 w-4 ring-5',
    '3xl': 'h-5 w-5 ring-5',
    'positions': {
      'top-right': 'top-0 right-0',
      'bottom-right': 'bottom-0 right-0',
      'top-left': 'top-0 left-0',
      'bottom-left': 'bottom-0 left-0',
    },
  },
  colors: {
    primary: 'bg-primary',
    success: 'bg-success',
    warning: 'bg-warning',
    danger: 'bg-danger',
    blue: 'bg-blue',
    red: 'bg-red',
    orange: 'bg-orange',
    yellow: 'bg-yellow',
    green: 'bg-green',
    mint: 'bg-mint',
    teal: 'bg-teal',
    cyan: 'bg-cyan',
    indigo: 'bg-indigo',
    purple: 'bg-purple',
    pink: 'bg-pink',
    gray: 'bg-gray',
  },
}
