export { StarterKit } from '@tiptap/starter-kit'
export { Placeholder } from '@tiptap/extension-placeholder'
export { FocusClasses as Focus } from '@tiptap/extension-focus'
export { Heading } from './Heading'
export { Document } from './Document'
export { TrailingNode } from './TrailingNode'
